import Head from "next/head";
import { Box } from "@chakra-ui/react";
import { Header, Sidebar } from "./index";

const Layout = ({ children }) => {
  return (
    <Box>
      <Head>
        <title>KanBan App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Box>
        <Sidebar />
        {children}
      </Box>
    </Box>
  );
};

export default Layout;
